import "./Projetos.css";
import ContainerProjetos from "./ContainerProjetos/ContainerProjetos";

export default function Projetos({ idiomaPT }) {
  return (
    <div className="formatacao-container">
      <h2>Projetos</h2>
      <ContainerProjetos idiomaPT={idiomaPT} titulo={'Creatures TCG'} imagem={'/projetos/creaturesProject.png'} site={'https://creaturestcg.netlify.app/'} repositorio={'https://github.com/JoaoVFBraga/CreaturesTCG'} texto={idiomaPT ? 'Sempre fui fã de jogos de cartas (TCG), então decidi criar um projeto onde fosse possível criar sua própria coleção de cartas. É possível criar, salvar, pesquisar e excluir cartas da sua coleção.' : "I've always been a fan of trading card games (TCG), so I decided to create a project where users can build their own card collection. It allows for creating, saving, searching, and deleting cards from the collection."} classe={''} tecnologia={true} />
      <ContainerProjetos idiomaPT={idiomaPT} titulo={'Switch Store'} imagem={'/projetos/switchProject.png'} site={'https://joaovfbraga.github.io/SwitchStoreProject/'} repositorio={'https://github.com/JoaoVFBraga/SwitchStoreProject'} texto={idiomaPT ? 'Switch Store é um e-commerce baseado no universo de Nintendo Switch, é possível pesquisar por produtos, adicionar ao carrinho, exibir cada produto de forma individual ao clicar sobre ele, e também possui uma página de login.' : '"Switch Store" is a Nintendo Switch-themed e-commerce platform where users can search for products, add items to their cart, view each product individually by clicking on it, and access a login page.'} classe={'inverter-flex'} />
      <ContainerProjetos idiomaPT={idiomaPT} titulo={'Padaria Brigadeiro'} imagem={'/projetos/padariaProject.png'} site={'https://padariabrigadeiro.netlify.app/'} repositorio={'https://github.com/JoaoVFBraga/PadariaBrigadeiro'} texto={idiomaPT ? 'Meu primeiro projeto com uso real. Foi desenvolvido para a Padaria Brigadeiro, localizada em Capivari-SP, possui um pouco da história dos sócios, apresentação dos produtos e área para contato.' : "My first real-use project. It was developed for Padaria Brigadeiro, located in Capivari-SP. It includes a bit of the owners' history, a presentation of the products, and a contact section."} classe={''} />
      <ContainerProjetos idiomaPT={idiomaPT} titulo={'MyGym'} imagem={'/projetos/gymProject.png'} site={'https://my-gym-jvfb.netlify.app/'} repositorio={'https://github.com/JoaoVFBraga/MyGym'} texto={idiomaPT ? 'MyGym é um projeto simples, consiste em um site de uma rede de academias, onde o foco foi o aprendizado de algumas animações baseadas em qual parte da página está sendo exibida.' : "MyGym is a simple project, consisting of a website for a gym chain, where the focus was on learning some animations based on which part of the page is being displayed."} />
      <ContainerProjetos idiomaPT={idiomaPT} titulo={idiomaPT ? 'JoKenPo na Web' : 'JoKenPo on the Web'} imagem={'/projetos/jokenpoProject.png'} site={'https://jokenpo-na-web.netlify.app/'} repositorio={'https://github.com/JoaoVFBraga/JoKenPoNaWeb'} texto={idiomaPT ? 'Após um tempo de estudo sobre JavaScript, decidi criar um jogo usando o conhecimento que havia adquirido, criei então um jogo de pedra, papel ou tesoura. Possui também um botão que apresenta as regras.' : "After some time studying JavaScript, I decided to create a game using the knowledge I had acquired, so I made a rock-paper-scissors game. It also includes a button that displays the rules."} classe={''} />
      <ContainerProjetos idiomaPT={idiomaPT} titulo={idiomaPT ? 'Descubra o número' : 'Guess the number'} imagem={'/projetos/descubraProject.png'} site={'https://descubraonumero-jvfb.netlify.app/'} repositorio={'https://github.com/JoaoVFBraga/jogo-acerte-o-numero'} texto={idiomaPT ? 'Usando os conhecimento adquiridos no livro "Lógica de Programação e Algoritmos com JavaScript", criei o jogo "Descubra o número", no qual você tem 5 chances para acertar um número aleatório.' : "Using the knowledge acquired from the book Programming Logic and Algorithms with JavaScript, I created the game Guess the Number, where you have 5 chances to guess a random number."} classe={'inverter-flex'} />
    </div>
  )
}